---
title: ""
output: html_document
---

# SPARC - Symbiotic Partners of Asgard Research Cruise

[SPARC](https://schmidtocean.org/cruise/searching-for-the-asgard/) was a 2025 research expedition aboard the [Schmidt Ocean Institute's R/V Falkor (too)](https://schmidtocean.org/) led by Drs. Brett Baker and Alyson Santoro. Our goal was to explore the Uruguayan seas in search of living Asgard archaea, a group of microbes considered the closest known relatives of eukaryotes, and their bacterial partners, to better understand how complex life emerged from simple cells. 

<center><iframe width="560" height="315" src="https://www.youtube.com/embed/Jy_boPdY0zo?si=RoROTZkBKWxXYgZt" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></center>

The origin of the first eukaryotic cell remains one of biology’s biggest unsolved questions. Recent genomic work shows that Asgard archaea share key genes with eukaryotes, suggesting they may resemble the microbes involved in eukaryogenesis, the evolutionary process in which an archaeal host and bacterial symbiont merged to form the earliest complex cell. During SPARC, we focused on identifying Hodarchaeales, an Asgard lineage thought to thrive in coastal mud where freshwater and seawater meet, including the mouth of Urugauy's Río de la Plata.  

Working with the Santoro Lab, Dr. Jason Graff used cell-sorting flow cytometry to isolate and purify archaeal cells for downstream analyses including cultivation and sequencing. We also used this expedition as a cruise-of-opportunity to advance our [PACE Validation Science Team research](https://nbaetge.github.io/pvst.html), collecting optical and biogeochemical measurements to "ground-truth" satellite observations. Read more about our work off the coast of Urugauy from Dr. Graff's NASA [Notes from the Field](https://science.nasa.gov/blogs/notes-from-the-field/2026/04/27/off-uruguay-pace-partners-connect-data-from-satellite-and-sea/). 

<center><iframe width="560" height="315" src="https://www.youtube.com/embed/mgmEh_qag5E?si=WYOlCZ9XiTDt5iiD" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></center>


