---
title: ""
output: html_document
---

[Google sheet of funding opportunities - last update 10-2024](https://docs.google.com/spreadsheets/d/1BaC0sX7I8_mMcXxIThEM2kZgSUqi7-l_BHZe_CUvuhw/edit?gid=194681346#gid=194681346)

# ASU-BIOS undergraduate support and opportunities

- [Research Experiences for Undergraduates (REU) at BIOS](https://bios.asu.edu/education/reu)

- [BIOS Internships](https://bios.asu.edu/education/internships-university-students)

- [Summer courses at Bermuda Institute of Ocean Sciences](https://www.us-ocb.org/science-support/student-opportunities/)

# External undergraduate support and opportunities

- [NSF Education & Training Application (ETAP) is a secure online platform that connects applicants to NSF-funded opportunities](https://etap.nsf.gov/search)

- [NSF Ocean Sciences Research Experiences for Undergraduates (REU)](https://hmsc.oregonstate.edu/research-experiences-undergraduates)

- [NASA undergraduate student funding opportunities](https://science.nasa.gov/learn/learner-opportunities/#undergrad)

- [Ford Foundation Predoctoral Fellowship](https://www.nationalacademies.org/our-work/ford-foundation-fellowships)

- [NOAA undergraduate funding opportunities](http://www.noaa.gov/opportunities/student-opportunities) 

- [NOAA Ernest F. Hollings and EPP Undergraduate Scholarship Programs](https://oedwebdbapps.iso.noaa.gov/uspa/)

- [The William M. Lapenta NOAA Student Internship Program](https://vlab.noaa.gov/web/lapenta-internship-program)

- [AMS Women in Science Scholarship](https://www.ametsoc.org/index.cfm/ams/information-for/students/ams-scholarships-and-fellowships/women-in-science-scholarship/)

- [AMS Scholarship for Underserved Communities](https://www.ametsoc.org/index.cfm/ams/information-for/students/ams-scholarships-and-fellowships/ams-scholarship-for-underserved-communities-formerly-minority-scholarship/)

- [MBARI Summer Internships](https://www.mbari.org/about/careers/internships/how-to-apply/)

- [Scholarships in marine science for visiting undergraduate students at Duke](https://nicholas.duke.edu/marinelab/academics/undergraduate/scholarships-financial-aid)

- [ASLO Multicultural Program](https://www.aslo.org/opportunities-in-aslo/aslo-multicultural-program/)

- [UCSB Promise Fellowship Program](https://www.graddiv.ucsb.edu/promise-fellowship-program)